import {TaskStatus} from './types';
import {TaskConstructor} from './utils';

const tasks = [
  new TaskConstructor(
      '1',
      'Задача 1',
      TaskStatus.ON_APPROVAL,
      'Инна',
      'Артем',
      new Date('2020-04-01'),
  ),
  new TaskConstructor(
      '2',
      'Задача 2',
      TaskStatus.IN_PROGRESS,
      'Ваня',
      'Сава',
      new Date('2020-04-02'),
  ),
  new TaskConstructor(
      '3',
      'Задача 3',
      TaskStatus.COMPLETED,
      'Сава',
      'Ваня',
      new Date('2020-04-03'),
  ),
  new TaskConstructor(
      '4',
      'Задача 4',
      TaskStatus.ON_APPROVAL,
      'Артем',
      'Инна',
      new Date('2020-04-04'),
  ),
  new TaskConstructor(
      '5',
      'Задача 5',
      TaskStatus.IN_PROGRESS,
      'Инна',
      'Артем',
      new Date('2020-04-05'),
  ),
  new TaskConstructor(
      '6',
      'Задача 6',
      TaskStatus.COMPLETED,
      'Ваня',
      'Сава',
      new Date('2020-04-06'),
  ),
  new TaskConstructor(
      '7',
      'Задача 7',
      TaskStatus.ON_APPROVAL,
      'Сава',
      'Ваня',
      new Date('2020-04-07'),
  ),
  new TaskConstructor(
      '8',
      'Задача 8',
      TaskStatus.IN_PROGRESS,
      'Артем',
      'Инна',
      new Date('2020-04-08'),
  ),
  new TaskConstructor(
      '9',
      'Задача 9',
      TaskStatus.COMPLETED,
      'Инна',
      'Артем',
      new Date('2020-04-09'),
  ),
  new TaskConstructor(
      '10',
      'Задача 10',
      TaskStatus.ON_APPROVAL,
      'Ваня',
      'Сава',
      new Date('2020-04-10'),
  ),
  new TaskConstructor(
      '11',
      'Задача 11',
      TaskStatus.IN_PROGRESS,
      'Сава',
      'Ваня',
      new Date('2020-04-11'),
  ),
  new TaskConstructor(
      '12',
      'Задача 12',
      TaskStatus.COMPLETED,
      'Артем',
      'Инна',
      new Date('2020-04-12'),
  ),
  new TaskConstructor(
      '13',
      'Задача 13',
      TaskStatus.ON_APPROVAL,
      'Инна',
      'Артем',
      new Date('2020-04-13'),
  ),
  new TaskConstructor(
      '14',
      'Задача 14',
      TaskStatus.IN_PROGRESS,
      'Ваня',
      'Сава',
      new Date('2020-04-14'),
  ),
  new TaskConstructor(
      '15',
      'Задача 15',
      TaskStatus.COMPLETED,
      'Сава',
      'Ваня',
      new Date('2020-04-15'),
  ),
  new TaskConstructor(
      '16',
      'Задача 16',
      TaskStatus.ON_APPROVAL,
      'Артем',
      'Инна',
      new Date('2020-04-16'),
  ),
];

export default tasks.sort(() => Math.random() < 0.5 ? -1 : 1);
